# WITS Automation Configuration
credentials:
  email: "owaismujtaba@ugr.es"
  password: "Abuji@2580"
  query_name: "Auto2007New"

urls:
  login: "https://wits.worldbank.org/WITS/WITS/Restricted/Login.aspx"
  advanced_query: "https://wits.worldbank.org/WITS/WITS/Restricted/AdvancedQuery/TradeData.aspx" # This is a guess, I will verify it.

automation:
  browser: "chromium"
  headless: false


iso3_to_country : {
    "ABW": "Aruba",
    "AFG": "Afghanistan",
    "AGO": "Angola",
    "AIA": "Anguila",
    "ALB": "Albania",
    "AND": "Andorra",
    "ANT": "Netherlands Antilles",
    "ARE": "United Arab Emirates",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ASM": "American Samoa",
    "ATF": "Fr. So. Ant. Tr",
    "ATG": "Antigua and Barbuda",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BAT": "Br. Antr. Terr",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BFA": "Burkina Faso",
    "BGD": "Bangladesh",
    "BGR": "Bulgaria",
    "BHS": "Bahamas, The",
    "BIH": "Bosnia and Herzegovina",
    "BLR": "Belarus",
    "BLX": "Belgium-Luxembourg",
    "BLZ": "Belize",
    "BMU": "Bermuda",
    "BOL": "Bolivia",
    "BRA": "Brazil",
    "BRB": "Barbados",
    "BRN": "Brunei",
    "BTN": "Bhutan",
    "BWA": "Botswana",
    "CAF": "Central African Republic",
    "CAN": "Canada",
    "CCK": "Cocos (Keeling) Islands",
    "CHE": "Switzerland",
    "CHL": "Chile",
    "CHN": "China",
    "CIV": "Cote d'Ivoire",
    "CMR": "Cameroon",
    "COG": "Congo, Rep.",
    "COK": "Cook Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPV": "Cape Verde",
    "CRI": "Costa Rica",
    "CSK": "Czechoslovakia",
    "CUB": "Cuba",
    "CXR": "Christmas Island",
    "CYM": "Cayman Islands",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DDR": "German Democratic Republic",
    "DEU": "Germany",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DNK": "Denmark",
    "DOM": "Dominican Republic",
    "DZA": "Algeria",
    "ECU": "Ecuador",
    "EGY": "Egypt, Arab Rep.",
    "ERI": "Eritrea",
    "ESH": "Western Sahara",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia (excludes Eritrea)",
    "ETF": "Ethiopia (includes Eritrea)",
    "EUN": "European Union",
    "FIN": "Finland",
    "FJI": "Fiji",
    "FLK": "Falkland Island",
    "FRA": "France",
    "FRE": "Free Zones",
    "FRO": "Faeroe Islands",
    "FSM": "Micronesia, Fed. Sts.",
    "GAB": "Gabon",
    "GAZ": "Gaza Strip",
    "GBR": "United Kingdom",
    "GEO": "Georgia",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GIN": "Guinea",
    "GLP": "Guadeloupe",
    "GMB": "Gambia, The",
    "GNB": "Guinea-Bissau",
    "GNQ": "Equatorial Guinea",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GRL": "Greenland",
    "GTM": "Guatemala",
    "GUF": "French Guiana",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HKG": "Hong Kong, China",
    "HND": "Honduras",
    "HRV": "Croatia",
    "HTI": "Haiti",
    "HUN": "Hungary",
    "IDN": "Indonesia",
    "IND": "India",
    "IOT": "British Indian Ocean Ter.",
    "IRL": "Ireland",
    "IRN": "Iran, Islamic Rep.",
    "IRQ": "Iraq",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JOR": "Jordan",
    "JPN": "Japan",
    "JTN": "Jhonston Island",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyz Republic",
    "KHM": "Cambodia",
    "KIR": "Kiribati",
    "KNA": "St. Kitts and Nevis",
    "KN1": "Saint Kitts-Nevis-Anguilla-Aru",
    "KOR": "Korea, Rep.",
    "KWT": "Kuwait",
    "LAO": "Lao PDR",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LCA": "St. Lucia",
    "LIE": "Liechtenstein",
    "LKA": "Sri Lanka",
    "LSO": "Lesotho",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "LVA": "Latvia",
    "MAC": "Macao",
    "MAR": "Morocco",
    "MCO": "Monaco",
    "MDA": "Moldova",
    "MDG": "Madagascar",
    "MDV": "Maldives",
    "MEX": "Mexico",
    "MID": "Midway Islands",
    "MLI": "Mali",
    "MLT": "Malta",
    "MMR": "Myanmar",
    "MNG": "Mongolia",
    "MNP": "Northern Mariana Islands",
    "MOZ": "Mozambique",
    "MRT": "Mauritania",
    "MSR": "Montserrat",
    "MTQ": "Martinique",
    "MUS": "Mauritius",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "NAM": "Namibia",
    "NCL": "New Caledonia",
    "NER": "Niger",
    "NFK": "Norfolk Island",
    "NGA": "Nigeria",
    "NIC": "Nicaragua",
    "NIU": "Niue",
    "NLD": "Netherlands",
    "NOR": "Norway",
    "NPL": "Nepal",
    "NRU": "Nauru",
    "NZE": "Neutral Zone",
    "NZL": "New Zealand",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PCN": "Pitcairn",
    "PCZ": "Fm Panama Cz",
    "PCE": "Pacific Islands",
    "PER": "Peru",
    "PHL": "Philippines",
    "PLW": "Palau",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "PMY": "Pen Malaysia",
    "PRK": "Korea, Dem. Rep.",
    "PRT": "Portugal",
    "PRI": "Puerto Rico",
    "PRY": "Paraguay",
    "PYF": "French Polynesia",
    "QAT": "Qatar",
    "REU": "Reunion",
    "ROM": "Romania",
    "RUS": "Russian Federation",
    "RWA": "Rwanda",
    "RYU": "Ryukyu Is",
    "SAU": "Saudi Arabia",
    "SBH": "Sabah",
    "SDN": "Sudan",
    "SEN": "Senegal",
    "SER": "Yugoslavia",
    "SGP": "Singapore",
    "SHN": "Saint Helena",
    "SIK": "SIKKIM",
    "SJM": "Svalbard and Jan Mayen Is",
    "SLB": "Solomon Islands",
    "SLE": "Sierra Leone",
    "SLV": "El Salvador",
    "SMR": "San Marino",
    "SOM": "Somalia",
    "SPE": "Special Categories",
    "SPM": "Saint Pierre and Miquelon",
    "SVK": "Slovak Republic",
    "SVN": "Slovenia",
    "SVR": "Fm Vietnam Rp",
    "SVU": "Soviet Union",
    "SUR": "Suriname",
    "SWK": "Sarawak",
    "SWE": "Sweden",
    "SWZ": "Swaziland",
    "SYR": "Syrian Arab Republic",
    "TAN": "Fm Tanganyik",
    "TCA": "Turks and Caicos Isl.",
    "TCD": "Chad",
    "TGO": "Togo",
    "THA": "Thailand",
    "TJK": "Tajikistan",
    "TKL": "Tokelau",
    "TKM": "Turkmenistan",
    "TMP": "East Timor",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TUV": "Tuvalu",
    "TWN": "Taiwan",
    "TZA": "Tanzania",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "UNS": "Unspecified",
    "URY": "Uruguay",
    "USA": "United States",
    "USP": "Us Msc.Pac.I",
    "UZB": "Uzbekistan",
    "VAT": "Holy See",
    "VCT": "St. Vincent and the Grenadines",
    "VEN": "Venezuela",
    "VGB": "British Virgin Islands",
    "VIR": "Virgin Islands (U.S.)",
    "VNM": "Vietnam",
    "VUT": "Vanuatu",
    "WAK": "Wake Island",
    "WLD": "World",
    "WLF": "Wallis and Futura Isl.",
    "WSM": "Samoa",
    "YDR": "Yemen Democratic",
    "YEM": "Yemen, Rep.",
    "YUG": "Yugoslavia, FR (Serbia/Montenegro)",
    "ZAF": "South Africa",
    "ZAR": "Congo, Dem. Rep.",
    "ZMB": "Zambia",
    "ZPM": "Fm Zanz-Pemb",
    "ZWE": "Zimbabwe",
    "ZW1": "Fm Rhod Nyas"
}
